# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sergei Volkov
title: Software Engineer
email: wolfserik111@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Software Engineer specializing in Quality Assurance, automation, CI/CD, and DevOps practices. My diverse background spans multiple project types, including web systems, desktop applications, system software (such as binary translators), and exposure to the cryptocurrency field (short part-time experience).

  In addition to my technical expertise, I have several years of experience as a Team Leader, where I focused on guiding teams towards automation-driven solutions. I strongly advocate for reducing manual processes wherever possible, while recognizing the value of manual intervention when necessary.
  
  I am passionate about contributing to the success of innovative projects and continuously seek opportunities to drive efficiency and quality.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: HUAWEI
        link: huawei.com
        # link_text: boringcompany.com
        sub_title: Lead Software Engineer
        caption: April 2020 - Present<br>(4 years 11 month)
        description: | # this will include new lines to allow paragraphs
            Promoted to lead the team responsible for infrastructure improvements and application quality assurance, with a focus on the binary translator application.
            
            Key Responsibilities:
            - Lead a team (up to 5 engineers), along with mentoring interns.
            - Design, enhance, and maintain systems for functional, performance, and pre-/post-commit testing.
            - Develop and manage CI/CD pipelines, ensuring robust testing and streamlined deployments.
            - Ensure application quality assurance and handle release management.
            - Maintain and improve the development and testing infrastructure.
            
            Key Achievements:
            - Implemented daily regression test runs with detailed reporting for team insights.
            - Significantly increased regression test coverage, including the number of performance benchmarks.
            - Set up virtualization for bare-metal hosts using KVM-QEMU, optimizing resource allocation and enhancing infrastructure scalability.
            - Introduced a load-balancing mechanism for Jenkins agents, improving resource utilization.
            - Configured logging and monitoring systems (Logstash, Grafana).
            - Successfully released multiple stable versions of the application.
            
            Technologies: Python3, Bash, Linux, Jenkins, Docker, KVM-QEMU, Ansible, GitLab, ELK.
     
      - layout: left
        border: weak
        title: HUAWEI
        link: huawei.com
        sub_title: Senior Software Engineer
        caption: November 2019 - April 2020<br>(6 months)
        description: | # this will include new lines to allow paragraphs
            Focused on developing robust testing models and enhancing the CI/CD ecosystem.
            
            Key Responsibilities:
            - Develop a testing model and define the testing strategy.
            - Increase regression test coverage and automated regression workflows.
            - Contribute to the creation of CI/CD pipelines for efficient testing and deployments.
            
            Key Achievements:
            - Standardized functional testing approaches and led the process of rewriting old scripts to a new standard (Python3).
            - Developed a CI system from scratch using Jenkins, incorporating Infrastructure as Code principles (pipelines, shared libraries).
            - Built a Docker-based infrastructure to support scalable build and test launches.

      - layout: left
        border: weak
        title: Acronis
        link: acronis.com
        # link_text: boringcompany.com
        sub_title: Software Developer in Test
        caption: December 2017 - November 2019<br>(2 years)
        description: | # this will include new lines to allow paragraphs
            In the first year, I worked as part of the Automation QA team, and later transitioned to developing automation within the development team, with one assistant.
            
            Key Responsibilities:
            - Develop a testing framework using Python3.
            - Design and implement new automated tests, as well as maintain and support existing tests (Test frameworks: Pytest, Unittest; Test types: backend RESTAPI, network, installation, upgrade).
            - Analyze test runs and identifiy weaknesses in the test architecture (e.g., complex test logic, poor logging) to optimize the analysis process and reduce test run time.
            - Develop and enhance test execution infrastructure using Jenkins, Docker, VMware, and HyperV.

      - layout: left
        border: weak
        title: Agency of Economic Information PRIME
        link: 1prime.ru
        sub_title: Senior QA Engineer
        caption: September 2016 - January 2018<br>(1 years 5 months)
        description: | # this will include new lines to allow paragraphs
            As a Senior QA Engineer, I worked with various teams within the department, each focusing on different services, requiring multitasking and adaptability.
            
            Key Responsibilities:
            - Functional testing across various services, including:
                 - ETL-procedures (MS SQL, Pentaho)
                 - Web services (REST, SOAP, POSTMAN)
                 - Website features (Frontend)
                 - Win-application (Client for economic information display).
            - Bugs management, preparation of test cases and test plans.
        
      - layout: left
        title: Insentry
        link:  insentry.io/en
        sub_title: QA Engineer
        caption: July 2015 - September 2016<br>(1 year 3 months)
        description: | # this will include new lines to allow paragraphs
            The project involved a video surveillance system with integrated computer vision.
            
            Key Responsibilities:
            - Functional testing of the following components:
                - Client (Win-application)
                - Server (Win-service with Web-UI)
                - Archive (Win-service with Web-UI)
                - Analytics (Computer vision application with distributed load)
                - Voice communication subsystem (IP-telephony module integrated into the client)
            - Execute integration testing of the current components.
            - Create detailed test plans and test cases.
            - Configure product environments and demo stands for demonstrations.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        link:  eng.miet.ru
        caption: 2010 - 2015
        description: |
            **National Research University of Electronic Technology (MIET), Moscow**
            
            Specialist degree, Departments of Micro-Devices and Technical Cybernetics, Applied Maths

  - title: Key skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Program languages:** Python, Groovy, Bash<br>
      **Version control:** Git, SVN<br>
      **Virtualization:** Docker, KVM, VMware, HyperV<br>
      **Operation systems:** Linux, Windows<br>
      **CI\CD tools:** Jenkins, Gitlab<br>
      **Configuration management:** Ansible<br>
      **Monitoring systems:** Grafana, ELK (Elasticsearch, Logstash, Kibana)<br>
      **Task management:** Jira, Bugzilla<br>
      **Management skills:** task decomposition, process management, team management, task delegation, mentoring<br> 
      **Speaking languages:** Russian — Native, English — B2
      

  - title: Additional information
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Soft skills:** strong analytical and problem-solving abilities; effective team collaboration and communication; ability to multitask and manage work priorities; 
                       adaptability and a commitment to continuous learning; conflict resolution and maintaining a positive work environment.
      
      **Personal interests:** traveling, football, spending time with family.
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
